### ISSUE TITLE
Unable to sync content

### ISSUE THREAD

**Issue by sejoker** [jsebfranck/contentful-publication#7]
node version : 0.10
system: ubuntu 14
sync models between 2 Contentful spaces works without error but syncing content fails with error:

`2015-06-12T15:22:17.715Z - debug: Processing sync response
Unhandled rejection OperationalError: {
  "sys": {
    "type": "Error",
    "id": "NotFound"
  },
  "message": "The resource could not be found.",
  "details": {
    "sys": {
      "type": "Space"
    }
  },
  "requestId": "9f3-2135316989"
}`

```
at BufferList.<anonymous> (/home/vagrant/.nvm/v0.10.38/lib/node_modules/contentful-publication/node_modules/questor/index.js:40:25)
at BufferList.end (/home/vagrant/.nvm/v0.10.38/lib/node_modules/contentful-publication/node_modules/questor/node_modules/bl/bl.js:75:10)
at IncomingMessage.onend (_stream_readable.js:502:10)
at IncomingMessage.g (events.js:180:16)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:448:13)
```

Any ideas how to digest the problem?

**Comment by jvinai** [comment]
I'm pretty sure the content you want to synch require an other content who has been deleted.
